number=(1,2,3,4)
numbers=list((1,2,3,4,5))
fruits=['apples','oranges','grapes']
print(number)
print(numbers)

print(fruits[1])
print(len(fruits))

fruits.append('mango')
print(fruits)
fruits.remove('apples')
print(fruits)
fruits.insert(0,'strawberry')
print(fruits)
fruits.pop(2)
print(fruits)
fruits.reverse()
print(fruits)
fruits.sort()
print(fruits)
fruits.sort(reverse=True)
print(fruits)